### ISSUE TITLE
TypeError: object.init() takes exactly one argument (the instance to initialize)

### ISSUE THREAD

**Issue by xielaiban** [Jai-wei/YOLOv8-PySide6-GUI#4]
C:\Users\yujunyu\.conda\envs\pytorch\python.exe D:/PycharmProject(D)/CIFAR10-GUI/YOLOv8-PySide6-GUI-main/YOLOv8-PySide6-GUI-main/main.py
Traceback (most recent call last):
  File "D:\PycharmProject(D)\CIFAR10-GUI\YOLOv8-PySide6-GUI-main\YOLOv8-PySide6-GUI-main\main.py", line 697, in <module>
    Home = MainWindow()
  File "D:\PycharmProject(D)\CIFAR10-GUI\YOLOv8-PySide6-GUI-main\YOLOv8-PySide6-GUI-main\main.py", line 300, in __init__
    super(MainWindow, self).__init__(parent)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

Process finished with exit code 1

**Comment by Liam-Merouin** [comment]
您好，请问您解决这个问题了嘛？

**Comment by Jai-wei** [comment]
The code in `main.py` : `super(MainWindow, self).init(parent)`, to `super(MainWindow, self).__init__()`

**Comment by Jai-wei** [comment]
Can also try : `pip install ultralytics==8.0.48`
